// <auto-generated />
using System;
using MedicineInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicineInventory.Infrastructure.Migrations
{
    [DbContext(typeof(MedicineDbContext))]
    [Migration("20260624004952_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MedicineInventory.Domain.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Medicines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Cipla",
                            ExpiryDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Paracetamol 500mg",
                            Notes = "Used for fever and pain relief",
                            Price = 25.50m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Sun Pharma",
                            ExpiryDate = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Azithromycin 250mg",
                            Notes = "Antibiotic medicine",
                            Price = 120.00m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Himalaya",
                            ExpiryDate = new DateTime(2027, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Vitamin D3",
                            Notes = "Supplement",
                            Price = 180.75m,
                            Quantity = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
